name = "lehakwe-email-worker"
main = "src/index.ts"
compatibility_date = "2025-06-09"
account_id = "c63d3d6d8c17db7487ab40b81d5e29d1"

[[d1_databases]]
binding = "DB"
database_name = "lehakwe-db"
database_id = "aaafb847-a046-4bf1-8325-d41e6244a505"

[[r2_buckets]]
binding = "EMAIL_STORE"
bucket_name = "lehakwe-emails"

[vars]
FORWARD_EMAILS = "kekelebaka@outlook.com,chiefops26@gmail.com"
AUTO_REPLY_ENABLED = "true"
SENDING_DOMAIN = "lehakwedaycare.co.za"
ALLOWED_ORIGIN = "https://mail.lehakwedaycare.co.za"
